name: Update user-agent
description: Sets the version number in the default user-agent header.

inputs:
  branch:
    description: Branch to checkout and update.
    required: true

runs:
  using: composite
  steps:
  - name: Checkout code
    uses: actions/checkout@v4
    with:
      ref: ${{ inputs.branch }}
  - name: Configure user-agent
    run: |
      version=$(jq -r '."."' .github/release-manifest.json)
      version=${version#v}
      sed -i "s/unfunco\/anthropic-sdk-go@v[0-9]*\.[0-9]*\.[0-9]*/unfunco\/anthropic-sdk-go@v$version/" anthropic.go
      git config --local user.name "David Letterman"
      git config --local user.email "48985810+david-letterman@users.noreply.github.com"
      git add anthropic.go
      git commit -m "Configure user-agent version number"
      git push
    shell: bash
