name: CI

on:
  push:
    branches:
    - main
    paths-ignore:
    - .editorconfig
    - .gitignore
    - CHANGELOG.md
    - LICENSE.md
    - README.md

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Check formatting
      run: test -z "$(go fmt ./...)"
    - name: Look for suspicious constructs
      run: test -z "$(go vet ./...)"
    - name: Run tests
      run: go test -v ./...

  release:
    name: Release?
    needs: [ verify ]
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Prepare a release
      id: release
      uses: google-github-actions/release-please-action@v4
      with:
        config-file: .github/release-config.json
        manifest-file: .github/release-manifest.json
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Configure version
      if: ${{ steps.release.outputs.prs_created }}
      run: |
        version=${{ steps.release.outputs.tag_name }}
        version=${version#v}
        sed -i "s/unfunco\/anthropic-sdk-go@v[0-9]*\.[0-9]*\.[0-9]*/unfunco\/anthropic-sdk-go@v$version/" anthropic.go
        git config user.name "David Letterman"
        git config user.email "48985810+david-letterman@users.noreply.github.com"
        git add anthropic.go
        git commit -m "Configure version number"
        git push
