name: PR

on:
  pull_request:
    branches:
    - main
    paths-ignore:
    - .editorconfig
    - .gitignore
    - CHANGELOG.md
    - LICENSE.md
    - README.md

jobs:
  verify-go:
    name: Verify Go
    permissions:
      contents: read
    uses: unfunco/meta/.github/workflows/verify-go.yaml@dc15f9a32fe01b1b7cc44e095ab9e9bdd98bb0b7

  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Lint source code
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest
    - name: Run tests with coverage
      run: go test -cover -v ./...
